export const AUTH = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  REFRESH_ACCESS_TOKEN: 'REFRESH_ACCESS_TOKEN',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  ONBOARD_COMPLETE: 'ONBOARD_COMPLETE',
};

export const LEADERBOARD = {
  GET_LEADERBOARD: 'GET_LEADERBOARD',
};

export const REVIEWS = {
  GET_REVIEWS: 'GET_REVIEWS',
};

export const BIO = {
  SEND_BIO: 'SEND_BIO',
  RESET_BIO: 'RESET_BIO',
  LOAD_CONTACT: 'LOAD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
};

export const PULSE = {
  SEND_PULSE: 'SEND_PULSE',
  RESET_PULSE: 'RESET_PULSE',
};
